#!/bin/sh
#
# Setup default AP network or connect to the previous network as a client
# Default AP configuration is assumed to be in /etc/config/wireless-ap-only
#
CONFIG="/boot/wifi_config.txt"
BACKUP_CONFIG="/root/.wifi_config.txt"
HIGH_PIN=20
TEST_PIN=26
TIMEOUT=30
SLEEP=3
TRIES=$((TIMEOUT / SLEEP))

echo $HIGH_PIN > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio$HIGH_PIN/direction
echo 1 > /sys/class/gpio/gpio$HIGH_PIN/value
echo $TEST_PIN > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio$TEST_PIN/direction

if [ ! -f $CONFIG ]; then
  logger -t wifi "Configuration file missing, entering AP only mode"
  cp $BACKUP_CONFIG $CONFIG
fi

if [ `cat /sys/class/gpio/gpio$TEST_PIN/value` -eq 0 ]; then
  logger -t wifi "Jumper reset, entering AP only mode"
  cp $BACKUP_CONFIG $CONFIG
fi

source $CONFIG

sta_err=0
echo $erase_wifi_configuration
if [ $erase_wifi_configuration -eq 1 ]; then
  logger -t wifi "Erasing wifi configuration, entering AP only mode"
  cp /etc/config/wireless_ap_only /etc/config/wireless
  wifi up
else
  sleep 5
  while [ $(iwinfo | grep -c "ESSID: unknown") -ge 1 ]; do
    logger -t wifi "Failed to connect to the stored wifi network $sta_err/$TRIES"
    let sta_err=$sta_err+1
    sleep $SLEEP
    if [ $((sta_err * SLEEP)) -ge $TIMEOUT ]; then
      logger -t wifi "Failed to connect to the stored wifi network, getting back to the fallback AP configuration"
      cp /etc/config/wireless_ap_only /etc/config/wireless
      wifi up
      break
    fi
  done
fi
if [ $(iwinfo | grep -c "ESSID: unknown") -ne 1 ]; then
  logger -t wifi "WIFI SSID: $(iwinfo | grep ESSID | cut -d \" -f 2)"
fi

