#!/bin/sh /etc/rc.common
# Border Router startup

START=99

start() {
        echo BORDER ROUTER START
        /bin/sh /root/start_border_router.sh
}

stop() {
        echo BORDER ROUTER STOP
        killall wpantund
		killall tayga
		killall prefix_border_router.sh
}
